const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const matter=require('gray-matter');
const {buildManifest}=require('../build');
const root=path.resolve(__dirname,'..');
const manifest=buildManifest(root);
test('all content assets, galleries, banners and embeds survive migration',()=>{
 for(const page of manifest.pages){
  const refs=[page.banner,page.sound,...[...page.body.matchAll(/!\[[^\]]*\]\(([^)]+)\)|(?:images|embed)\{([^}]+)\}|!\[sound:([^\]]+)\]/g)].map(m=>m[1]||m[3]||m[2].split(',')[0])].filter(Boolean);
  for(const ref of refs){if(/^https?:/.test(ref))continue;assert.ok(fs.existsSync(path.resolve(root,page.assetBase,ref.split('#')[0].trim())),`${page.slug}: ${ref}`);}
  assert.equal(matter(fs.readFileSync(path.join(root,page.authorSource),'utf8')).content,page.body);
  assert.equal(fs.readFileSync(path.join(root,page.source),'utf8'),page.body);
 }
 assert.ok(manifest.pages.every(p=>!p.source.includes('/drafts/')&&!p.source.includes('/.obsidian/')));
});
test('known internal links are semantic and point to published pages',()=>{
 const slugs=new Set(manifest.pages.map(p=>p.slug));
 for(const page of manifest.pages){for(const match of page.body.matchAll(/\]\(#\/([^\s)]+)\)/g))assert.ok(slugs.has(match[1]),`${page.slug}: ${match[1]}`);}
});
test('professional shell is derived from shared root shell',()=>{
 const shared=fs.readFileSync(path.join(root,'index.html'),'utf8');
 const work=fs.readFileSync(path.join(root,'work/index.html'),'utf8');
 assert.equal(work.replace('  <!-- Generated by npm run build; edit the root index.html instead. -->\n  <base href="../">\n',''),shared);
});
