const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
const base=process.env.SITE_URL||'http://127.0.0.1:5173';
async function run(){const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',args:['--no-sandbox']});const errors=[],results=[];fs.mkdirSync('.test-results/nav-links',{recursive:true});try{for(const width of [390,1440,1920]){const ctx=await browser.newContext({viewport:{width,height:900},isMobile:width===390,hasTouch:width===390}),page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));await ctx.addInitScript(()=>{window.printers=0;HTMLMediaElement.prototype.play=function(){if(this.src.endsWith('printer2.mp3'))printers++;return Promise.resolve();};});
async function ready(id){await page.waitForFunction(id=>document.querySelector('.content').dataset.pageId===id,id);}
async function click(key){if(width===390&&await page.locator('#index-toggle').getAttribute('aria-expanded')==='false')await page.locator('#index-toggle').click();await page.locator(`[data-group="${key}"]`).click({position:{x:8,y:8}});}
await page.goto(base+'/');await ready('home-professional');await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.querySelectorAll('.leftbg img')].map(img=>img.decode()));});await page.screenshot({path:`.test-results/nav-links/home-${width}.png`});
if(width!==390){const g=await page.evaluate(()=>Object.fromEntries(['.leftbg','.leftbg img','.material'].map(s=>{const e=document.querySelector(s),r=e.getBoundingClientRect();return[s,{x:r.x,width:r.width,height:r.height,size:getComputedStyle(e).backgroundSize}]})));assert.equal(g['.leftbg'].size,'100%');assert.ok(Math.abs(g['.material'].x-width*.42)<1);assert.ok(Math.abs(g['.leftbg img'].width-(width*.42-3))<1);results.push({width,geometry:g});}
await click('projects');await ready('projects-akashom');assert.equal(await page.evaluate(()=>activeGroup.key),'projects/akashom');assert.equal(await page.locator('.receipt-header').textContent(),'Akashom');assert.equal(await page.locator('[data-group="projects/akashom"]').getAttribute('aria-current'),'true');
await page.evaluate(()=>location.hash='#/projects/akashom/architecture');await ready('projects-akashom-architecture');await page.reload();await ready('projects-akashom-architecture');
await click('about');await ready('about-professional');await click('currents');await ready('currents-professional');await page.goBack();await ready('about-professional');await page.goForward();await ready('currents-professional');
await page.goto(base+'/personal/');await ready('home');for(const [key,id] of [['projects','projects-akashom'],['notes','notes-mindfill'],['archive','archive-consumption']]){await click(key);await ready(id);assert.equal(await page.evaluate(()=>activeGroup.key),await page.evaluate(id=>navigation.pageGroups.get(id).key,id));}
// Every visible container in each filtered view must normalize to a renderable leaf.
for(const shell of ['/','/personal/']){await page.goto(base+shell);await page.waitForFunction(()=>contentModel&&navigation);const cases=await page.evaluate(()=>[...navigation.catalog.values()].map(n=>({key:n.key,id:SiteNavigation.firstLeaf(n).id})));for(const item of cases){await page.evaluate(key=>location.hash='#/browse/'+key,item.key);await page.waitForFunction(id=>document.querySelector('.content').dataset.pageId===id&&!location.hash.includes('/browse/'),item.id);assert.ok(!page.url().includes('/browse/'));}}
// Fixtures exercise inline links without modifying authored prose.
await page.route('**/generated/pages/*',async r=>{const response=await r.fetch();await r.fulfill({response,body:(await response.text())+'\n\n[[about|About link]] [[currents]] [[personal:notes/philosophy/maximalist-soul-driver|Older philosophy]]\n'});});
for(const [shell,id] of [['/','about-professional'],['/personal/','about']]){await page.goto(base+shell);await page.waitForSelector('a[data-semantic-link]');const time=await page.evaluate(()=>performance.timeOrigin);await page.getByRole('link',{name:'About link',exact:true}).click();await ready(id);assert.equal(await page.evaluate(()=>performance.timeOrigin),time);assert.equal(await page.evaluate(()=>printers),0);assert.equal(new URL(page.url()).pathname,shell);await page.goBack();await page.waitForFunction(()=>document.querySelector('.content').dataset.pageId.startsWith('home'));await page.goForward();await ready(id);}
await page.goto(base+'/');await page.getByRole('link',{name:'Older philosophy',exact:true}).click();await ready('notes-philosophy-maximalist-soul-driver');assert.equal(new URL(page.url()).pathname,'/personal/');await ctx.close();}
assert.deepEqual(errors,[]);fs.writeFileSync('.test-results/nav-links/results.json',JSON.stringify({results,errors},null,2));console.log('PASS recursive visible-container resolution, selected owners, explicit routes/history, wiki links and desktop boundary geometry');}finally{await browser.close();}}
module.exports=run;if(require.main===module)run().catch(e=>{console.error(e);process.exitCode=1;});
