const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict'),fs=require('fs');
module.exports=async function(){const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',args:['--no-sandbox']});fs.mkdirSync('.test-results/stabilization',{recursive:true});try{for(const width of [390,1440]){const page=await browser.newPage({viewport:{width,height:900},isMobile:width===390,hasTouch:width===390,deviceScaleFactor:width===390?2:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));
async function route(slug){await page.evaluate(slug=>location.hash='#/'+slug,slug);await page.waitForFunction(slug=>location.hash==='#/'+slug&&contentModel.bySlug.get(slug)?.id===document.querySelector('.content').dataset.pageId,slug);await page.waitForTimeout(400);}
async function state(){const s=await page.evaluate(()=>({key:receiptState.selectedContainerId,count:receiptState.directLeafPages.length,eligible:receiptState.receiptEligible,tucked:receiptState.receiptTucked,header:document.querySelector('.receipt-header').textContent,label:activeGroup.label,display:getComputedStyle(document.getElementById('card-files-panel')).display,hidden:document.getElementById('card-files-panel').hidden}));assert.equal(s.header,s.label);assert.notEqual(s.display,'none');assert.equal(s.hidden,false);assert.equal(s.eligible,s.count>=2);assert.equal(s.tucked,s.count<2);return s;}
await page.goto('http://127.0.0.1:5173/#/home');await page.waitForSelector('.content-text p');await page.waitForTimeout(400);await state();
const ink=await page.locator('.content-text p').first().evaluate(e=>{let a=[];while(e){const c=getComputedStyle(e);a.push({filter:c.filter,transform:c.transform,blend:c.mixBlendMode,shadow:c.textShadow});e=e.parentElement;}return a;});if(width===390)for(const c of ink)assert.deepEqual(c,{filter:'none',transform:'none',blend:'normal',shadow:'none'});else assert.equal(ink[0].filter,'blur(0.1008px) drop-shadow(rgba(0, 0, 0, 0.19) 0px 0px 2.88px)');
await page.screenshot({path:`.test-results/stabilization/home-${width}.png`});
for(const slug of ['projects/darkroom','projects/akashom','projects/jivan','notes/mindfill','archive/consumption']){await route(slug);await state();}
await page.evaluate(()=>location.hash='#/browse/notes');await page.waitForFunction(()=>receiptState.selectedContainerId==='notes');assert.equal((await state()).count,0);
await page.evaluate(()=>location.hash='#/browse/projects/darkroom');await page.waitForFunction(()=>document.querySelector('.content').dataset.pageId==='projects-darkroom');assert.equal((await state()).count,1);
await page.evaluate(()=>location.hash='#/browse/projects/akashom');await page.waitForFunction(()=>document.querySelector('.content').dataset.pageId==='projects-akashom');assert.equal((await state()).count,4);
await page.evaluate(()=>setReceiptTucked(true));await route('projects/akashom/architecture');assert.equal(await page.evaluate(()=>receiptState.receiptTucked),true);assert.equal(await page.locator('#folder-line path').count(),0);await page.goBack();await page.waitForTimeout(450);assert.equal(await page.evaluate(()=>receiptState.receiptTucked),true);await page.goForward();await page.waitForTimeout(450);assert.equal(await page.evaluate(()=>receiptState.receiptTucked),true);
await page.evaluate(()=>window.receiptNode=document.querySelector('.receipt'));
for(let n=0;n<4;n++)for(const slug of ['browse/projects','projects/akashom','projects/jivan','projects/darkroom','projects/akashom']){await page.evaluate(slug=>location.hash='#/'+slug,slug);await page.waitForTimeout(55);}
await page.waitForTimeout(500);await state();assert.equal(await page.evaluate(()=>window.receiptNode===document.querySelector('.receipt')),true);
if(width===390)await page.locator('#index-toggle').click();await page.waitForTimeout(400);
const icon=await page.locator('[data-group="projects"]').evaluate(e=>{const c=getComputedStyle(e,'::before');return {content:c.content,border:c.borderLeftWidth,color:c.borderLeftColor};});assert.equal(icon.content,'""');assert.ok(parseFloat(icon.border)>0);if(width===390)assert.equal(await page.locator('#folder-line path').count(),0);
await page.screenshot({path:`.test-results/stabilization/index-${width}.png`});
if(width===390){
 const effects=await page.evaluate(()=>['.folder-link','.file-link','.receipt-header','.doc-dates','.content h2'].map(selector=>{let e=document.querySelector(selector),styles=[];while(e){const c=getComputedStyle(e);styles.push([c.filter,c.transform,c.textShadow,c.mixBlendMode]);e=e.parentElement;}return styles;}));
 for(const chain of effects)for(const values of chain)assert.deepEqual(values,['none','none','none','normal']);
}
const panel=page.locator('#card-files-panel'),start=await panel.boundingBox();
await page.evaluate(()=>setReceiptTucked(true));await page.waitForTimeout(100);const moving=await panel.boundingBox();assert.ok(moving.x<start.x);assert.equal(moving.height,start.height);assert.notEqual(await panel.evaluate(e=>getComputedStyle(e).display),'none');
await page.waitForTimeout(300);const tucked=await panel.boundingBox();assert.ok(tucked.x<moving.x);assert.equal(await page.locator('#folder-line path').count(),0);
await page.screenshot({path:`.test-results/stabilization/tucked-${width}.png`});
await page.evaluate(()=>setReceiptTucked(false));await page.waitForTimeout(400);assert.equal(await page.locator('#folder-line path').count(),0);assert.ok(Math.abs((await panel.boundingBox()).x-start.x)<1);

if(width===390)await page.locator('#index-close').click();await route('projects/darkroom');await page.locator('.image-viewer').first().scrollIntoViewIfNeeded();await page.locator('.image-viewer').first().click();await page.waitForFunction(()=>viewer?.opener.isOpen);await page.keyboard.press('ArrowRight');await page.keyboard.press('Escape');await page.waitForSelector('.pswp',{state:'detached'});
await page.goto('http://127.0.0.1:5173/work/#/projects/akashom/architecture');await page.waitForFunction(()=>document.querySelector('.content').dataset.pageId===receiptState.activePageId);await page.waitForTimeout(400);await state();assert.equal(await page.evaluate(()=>receiptState.directLeafPages.every(p=>p.audience.includes('professional'))),true);await page.reload();await page.waitForSelector('.receipt-header',{state:'attached'});await page.waitForTimeout(400);await state();assert.deepEqual(errors,[]);await page.close();}console.log('PASS stabilization: desktop/mobile ink, CSS icons, direct counts, persistent receipt DOM, manual tuck, history, rapid navigation, work routes and PhotoSwipe');}finally{await browser.close();}};

if(require.main===module)module.exports().catch(error=>{console.error(error);process.exitCode=1;});
