const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),matter=require('gray-matter');
const {buildManifest}=require('../build'),{createContentModel}=require('../js/content');
const base={id:'shared',slug:'about',title:'About',section:'about',type:'about',audience:['public','professional'],status:'active',published:true,created:'2026-09-29',variantGroup:'about'};
function build(t,pages){const root=fs.mkdtempSync(path.join(os.tmpdir(),'variants-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));fs.mkdirSync(path.join(root,'content'));pages.forEach((p,i)=>fs.writeFileSync(path.join(root,'content',i+'.md'),matter.stringify('<!-- author -->',JSON.parse(JSON.stringify(p)))));return buildManifest(root);}
const professional={...base,id:'about-professional',audience:['professional'],variant:'professional'},personal={...base,id:'about-personal',audience:['public'],variant:'personal'};
test('explicit identity variants share one logical slug',t=>{const m=build(t,[professional,personal]);assert.equal(createContentModel(m,'professional').resolve('about').id,professional.id);assert.equal(createContentModel(m,'public').resolve('about').id,personal.id);});
for(const page of [professional,personal])test('rejects duplicate '+page.variant+' variant',t=>assert.throws(()=>build(t,[page,{...page,id:'duplicate'}]),/ambiguous/));
test('ordinary duplicates remain invalid',t=>assert.throws(()=>build(t,[{...base,variantGroup:undefined},{...base,id:'second',variantGroup:undefined}]),/duplicate slug/));
test('explicit variant overrides declared shared fallback without duplicate navigation pages',t=>{const m=build(t,[base,professional]);assert.equal(createContentModel(m,'professional').resolve('about').id,professional.id);assert.equal(createContentModel(m,'professional').pages.length,1);assert.equal(createContentModel(m,'public').resolve('about').id,base.id);});
test('shared content needs no variant metadata',t=>{const m=build(t,[{...base,variantGroup:undefined}]);for(const mode of ['public','professional'])assert.equal(createContentModel(m,mode).resolve('about').id,'shared');});
test('variant audiences and groups cannot conceal ambiguous routes',t=>{assert.throws(()=>build(t,[{...professional,audience:['public','professional']}]),/variant audience/);assert.throws(()=>build(t,[{...professional,variantGroup:undefined}]),/requires variantGroup/);});
