const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
const base=process.env.SITE_URL||'http://127.0.0.1:5173',manifest=require('../manifest.json');
async function run(){const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/usr/bin/google-chrome',args:['--no-sandbox']});fs.mkdirSync('.test-results/views',{recursive:true});const errors=[],results=[];
try{for(const width of [390,430,1440,1920]){const mobile=width<900,ctx=await browser.newContext({viewport:{width,height:900},isMobile:mobile,hasTouch:mobile,deviceScaleFactor:mobile?2:1}),p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));
async function load(path,id=path.startsWith('/personal/')?'home':'home-professional'){await p.goto(base+path);await p.waitForFunction(id=>document.querySelector('.content')?.dataset.pageId===id,id);if(mobile&&await p.locator('#index-toggle').getAttribute('aria-expanded')==='true')await p.locator('#index-close').click();}
async function verifyRoot(){assert.equal(await p.evaluate(()=>currentAudience),'professional');assert.equal(await p.evaluate(()=>contentModel.pages.every(p=>p.published&&p.audience.includes('professional'))),true);assert.equal(await p.locator('[data-group^="archive"],[data-group="projects/darkroom"]').count(),0);assert.equal(await p.evaluate(()=>[...navigation.catalog.values()].every(n=>n.pages.every(p=>p.audience.includes('professional')))),true);}
await load('/');await verifyRoot();assert.equal(await p.locator('meta[name="robots"]').count(),0);
await load('/personal/');assert.equal(await p.evaluate(()=>contentModel.pages.length),manifest.pages.filter(p=>p.audience.includes('public')).length);assert.equal(await p.locator('meta[name="robots"]').getAttribute('content'),'noindex,follow');
await load('/work/?from=cv#/projects/akashom','projects-akashom');assert.equal(new URL(p.url()).pathname,'/');assert.equal(new URL(p.url()).search,'?from=cv');assert.equal(new URL(p.url()).hash,'#/projects/akashom');await verifyRoot();
await load('/work/');assert.equal(new URL(p.url()).pathname,'/');
await load('/#/archive/consumption','archive-consumption');assert.equal(new URL(p.url()).pathname,'/personal/');await p.reload();await p.waitForFunction(()=>document.querySelector('.content').dataset.pageId==='archive-consumption');
await load('/personal/#/projects/akashom','projects-akashom');if(mobile)await p.locator('#index-toggle').click();await p.locator('.file-link').nth(1).click();await p.waitForFunction(()=>document.querySelector('.content').dataset.pageId==='projects-akashom-visual-nonvisual-trailer');assert.equal(new URL(p.url()).pathname,'/personal/');await p.goBack();await p.waitForFunction(()=>document.querySelector('.content').dataset.pageId==='projects-akashom');await p.goForward();await p.waitForFunction(()=>document.querySelector('.content').dataset.pageId==='projects-akashom-visual-nonvisual-trailer');assert.equal(new URL(p.url()).pathname,'/personal/');
await load('/personal/#/notes/mindfill','notes-mindfill');assert.equal(await p.locator('.collection-index a').first().evaluate(a=>new URL(a.href).pathname),'/personal/');await p.locator('.collection-index a').first().click();await p.waitForFunction(()=>document.querySelector('.content').dataset.pageId!=='notes-mindfill');assert.equal(new URL(p.url()).pathname,'/personal/');
await load('/#/projects/akashom','projects-akashom');await verifyRoot();await p.evaluate(()=>location.hash='#/browse/archive');await p.waitForFunction(()=>document.querySelector('.content h2')?.textContent==='Page unavailable');assert.equal(new URL(p.url()).pathname,'/');await verifyRoot();
await p.goto(base+'/#/missing-page');await p.waitForFunction(()=>document.querySelector('.content h2')?.textContent==='Page unavailable');assert.equal(new URL(p.url()).pathname,'/');
for(const [slug,id,count] of [['projects/darkroom','projects-darkroom',1],['notes/philosophy','notes-philosophy',2],['projects/akashom','projects-akashom',4],['notes/mindfill','notes-mindfill',8]]){await load('/personal/#/'+slug,id);if(mobile)await p.locator('#index-toggle').click();await p.waitForTimeout(400);assert.equal(await p.locator('#receipt-toggle').count(),0);assert.equal(await p.evaluate(()=>receiptState.directLeafPages.length),count);assert.equal(await p.evaluate(()=>receiptState.receiptTucked),count<2);const r=await p.locator('.file-link').first().evaluate(e=>({line:parseFloat(getComputedStyle(e).lineHeight),width:document.querySelector('.receipt').getBoundingClientRect().width}));assert.ok(Math.abs(r.line-r.width/936*42.12)<.1);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),width);if(count>=2)await p.screenshot({path:`.test-results/views/receipt-${count}-${width}.png`});if(!mobile&&count>=2){await p.locator('#tuck-files-btn').click();assert.equal(await p.evaluate(()=>receiptState.receiptTucked),true);await p.locator('#tuck-files-btn').click();assert.equal(await p.evaluate(()=>receiptState.receiptTucked),false);}}
if(mobile){await p.evaluate(()=>setReceiptTucked(true));assert.equal(await p.evaluate(()=>receiptState.receiptTucked),false);const row=await p.locator('[data-group="notes/mindfill"]').boundingBox(),paper=await p.locator('.card').boundingBox();assert.ok(Math.abs(row.height-paper.width*69/1494)<.1);assert.equal(await p.locator('#folder-line path').count(),0);}
results.push({width,passed:true});await ctx.close();}
// Fixture project counts 2, 3 and 5 use existing generated bodies/assets; no authored content changes.
for(const count of [2,3,5]){const ctx=await browser.newContext({viewport:{width:390,height:900},isMobile:true,hasTouch:true}),p=await ctx.newPage();const fixture=structuredClone(manifest),sample=fixture.pages.find(p=>p.id==='projects-jivan');for(let i=1;i<count;i++)fixture.pages.push({...sample,id:`fixture-${i}`,slug:`projects/jivan/fixture-${i}`,title:`Entry ${i}`,navTitle:`Entry ${i}`,order:i+100});await p.route('**/manifest.json',r=>r.fulfill({json:fixture}));await p.goto(base+'/#/projects/jivan');await p.waitForFunction(()=>document.querySelector('.content').dataset.pageId==='projects-jivan');await p.locator('#index-toggle').click();await p.waitForTimeout(400);assert.equal(await p.locator('.file-link').count(),count);assert.equal(await p.evaluate(()=>receiptState.receiptTucked),false);await p.screenshot({path:`.test-results/views/receipt-${count}-390.png`});await ctx.close();}
assert.deepEqual(errors,[]);fs.writeFileSync('.test-results/views/results.json',JSON.stringify({results,errors},null,2));console.log('PASS root/personal/work modes, fallback, history, filtered navigation, persistent view links and receipt geometry at four widths');}finally{await browser.close();}}
module.exports=run;if(require.main===module)run().catch(e=>{console.error(e);process.exitCode=1;});
